DROP TABLE IF EXISTS likes, film_genres, genre, users, films;

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login varchar(55) UNIQUE NOT NULL,
	name varchar(255),
	email varchar(55) UNIQUE NOT NULL,
	birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
  id integer NOT NULL,
  friend_id integer NOT NULL,
  CONSTRAINT friends_id_user_id FOREIGN KEY (id) REFERENCES users(id),
  CONSTRAINT friends_friend_id_user_id FOREIGN KEY (friend_id) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS films (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(255),
  rating varchar(20) NOT NULL,
  releaseDate date NOT NULL,
  duration integer NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
  film_id integer NOT NULL,
  user_id integer NOT NULL,
  CONSTRAINT likes_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
  CONSTRAINT likes_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre (
  genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre varchar(20)
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id integer NOT NULL,
  genre_id integer NOT NULL,
  CONSTRAINT film_genres_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
  CONSTRAINT film_genres_genre_id FOREIGN KEY (genre_id) REFERENCES genre(genre_id) ON DELETE CASCADE
);